/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BreakReminder;

import PaginaPrincipalAdmin.Fondo;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author ozzIE
 */
       
public class SetBreak extends javax.swing.JFrame {
      
       
       DateFormat df6 = new SimpleDateFormat("HH:mm");
       String Box1 ="No Break",Box2 ="No Lunch",Box3 ="No Break";
       Date currentTime = new Date();
       Timer t1;
       Timer t2;
       Timer t3;
       Timer t4;
       Timer t5;
       Timer t6;
       int flag=0;
      
      
    public SetBreak() {
        initComponents();
         setLocationRelativeTo(null);
        setTitle("Break Reminder");
        setSize(500, 300);
        setResizable(false);
        //Fondo f = new Fondo();
        //this.add(f,BorderLayout.CENTER);
        //this.pack();                               
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Ingresa la hora de tus breaks y lunch:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setText("\t \n      Aqui puedes tomar notas de extra breaks, \n       desconecciones que tuviste o etcetera");
        jScrollPane6.setViewportView(jTextArea6);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jLabel1.setText("Ingresa tu primer break:");

        jLabel2.setText("Ingresa tu hora de Lunch:");

        jLabel3.setText("Ingresa tu segundo break:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Break", "4:30", "4:45", "5:00", "5:15", "5:30", "5:45", "6:00", "6:15", "6:30", "6:45", "7:00", "7:15", "7:30", "7:45", "8:00", "8:15", "8:30", "8:45", "9:00", "9:15", "9:30", "9:45", "10:00", "10:15", "10:30", "10:45", "11:00", "11:15", "11:30", "11:45", "12:00", "12:15", "12:30", "12:45", "13:00", "13:15", "13:30", "13:45", "14:00", "14:15", "14:30", "14:45", "15:00", "15:15", "15:30", "15:45", "16:00", "16:15", "16:30", "16:45", "17:00", "17:15", "17:30", "17:45", "18:00", "18:15", "18:30", "18:45", "19:00", "19:15", "19:30", "19:45", "20:00", "20:15", "20:30", "20:45", "21:00", "21:15", "21:30", "21:45", "22:00", "22:15", "22:30", "22:45", "23:00", "23:15", "23:30", "23:45" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Lunch", "4:30", "4:45", "5:00", "5:15", "5:30", "5:45", "6:00", "6:15", "6:30", "6:45", "7:00", "7:15", "7:30", "7:45", "8:00", "8:15", "8:30", "8:45", "9:00", "9:15", "9:30", "9:45", "10:00", "10:15", "10:30", "10:45", "11:00", "11:15", "11:30", "11:45", "12:00", "12:15", "12:30", "12:45", "13:00", "13:15", "13:30", "13:45", "14:00", "14:15", "14:30", "14:45", "15:00", "15:15", "15:30", "15:45", "16:00", "16:15", "16:30", "16:45", "17:00", "17:15", "17:30", "17:45", "18:00", "18:15", "18:30", "18:45", "19:00", "19:15", "19:30", "19:45", "20:00", "20:15", "20:30", "20:45", "21:00", "21:15", "21:30", "21:45", "22:00", "22:15", "22:30", "22:45", "23:00", "23:15", "23:30", "23:45" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Break", "4:30", "4:45", "5:00", "5:15", "5:30", "5:45", "6:00", "6:15", "6:30", "6:45", "7:00", "7:15", "7:30", "7:45", "8:00", "8:15", "8:30", "8:45", "9:00", "9:15", "9:30", "9:45", "10:00", "10:15", "10:30", "10:45", "11:00", "11:15", "11:30", "11:45", "12:00", "12:15", "12:30", "12:45", "13:00", "13:15", "13:30", "13:45", "14:00", "14:15", "14:30", "14:45", "15:00", "15:15", "15:30", "15:45", "16:00", "16:15", "16:30", "16:45", "17:00", "17:15", "17:30", "17:45", "18:00", "18:15", "18:30", "18:45", "19:00", "19:15", "19:30", "19:45", "20:00", "20:15", "20:30", "20:45", "21:00", "21:15", "21:30", "21:45", "22:00", "22:15", "22:30", "22:45", "23:00", "23:15", "23:30", "23:45" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, 91, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addGap(74, 74, 74))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {t1.restart();} 
        catch (Exception ex )
        {System.out.println("Este timer no se a inicializado");}
        try
        {t2.restart();} 
        catch (Exception ex )
        {System.out.println("Este timer no se a inicializado");}
        try
        {t3.restart();} 
        catch (Exception ex )
        {System.out.println("Este timer no se a inicializado");}
        try
        {t4.restart();} 
        catch (Exception ex )
        {System.out.println("Este timer no se a inicializado");}
        try
        {t5.restart();} 
        catch (Exception ex )
        {System.out.println("Este timer no se a inicializado");}
        try
        {t6.restart();} 
        catch (Exception ex )
        {System.out.println("Este timer no se a inicializado");}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Cancel Breaks
         try
        {t1.stop();} 
        catch (Exception ex )
        {System.out.println("Este timer no se a inicializado");}
        try
        {t2.stop();} 
        catch (Exception ex )
        {System.out.println("Este timer no se a inicializado");}
        try
        {t3.stop();} 
        catch (Exception ex )
        {System.out.println("Este timer no se a inicializado");}
        try
        {t4.stop();} 
        catch (Exception ex )
        {System.out.println("Este timer no se a inicializado");}
        try
        {t5.stop();} 
        catch (Exception ex )
        {System.out.println("Este timer no se a inicializado");}
        try
        {t6.stop();} 
        catch (Exception ex )
        {System.out.println("Este timer no se a inicializado");}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Aqui se confirman los breaks
        //  setVisible(false);
        if (!Box1.equals("No Break")){
            try
            {   Date currentTime = new Date();
                String currTime = df6.format(currentTime);
                String[] split = currTime.split(":");
                long CurrTimeInMins= TimeUnit.HOURS.toMinutes(Integer.parseInt(split[0]))+Integer.parseInt(split[1]);
                //Primer Break
                String[] split1 = Box1.split(":");
                long firstBreak= TimeUnit.HOURS.toMinutes(Integer.parseInt(split1[0]))+Integer.parseInt(split1[1]);

                //JOptionPane.showMessageDialog(null,"La Hora en minutos es:" + firstBreak);
                // Difference in time
                long break1= (firstBreak - CurrTimeInMins)-4;
                long break4= (firstBreak - CurrTimeInMins);

                if(firstBreak>=CurrTimeInMins)
                //
                //
                {t1= new Timer((int)TimeUnit.MINUTES.toMillis(break1), actions1);
                    t1.start();
                    flag=1;
                    t4= new Timer((int)TimeUnit.MINUTES.toMillis(break4), actions4);
                    t4.start();
                    flag=4;}
                else if(firstBreak<CurrTimeInMins){JOptionPane.showMessageDialog(null,"Tu primer break ya paso!");}

            }
            catch (Exception ex )
            {System.out.println("No se a seleccionado un break");}
        }
        else

        JOptionPane.showMessageDialog(null,"No ingresaste un primer break");

        if (!Box2.equals("No Lunch")){
            try
            {     Date currentTime = new Date();
                String currTime = df6.format(currentTime);
                String[] split = currTime.split(":");
                long CurrTimeInMins= TimeUnit.HOURS.toMinutes(Integer.parseInt(split[0]))+Integer.parseInt(split[1]);

                //Lunch
                String[] split2 = Box2.split(":");
                long lunch= TimeUnit.HOURS.toMinutes(Integer.parseInt(split2[0]))+Integer.parseInt(split2[1]);
                //Segundo Break

                //JOptionPane.showMessageDialog(null,"La Hora en minutos es:" + firstBreak);
                // Difference in time

                long break2= (lunch - CurrTimeInMins)-4;
                long break5= (lunch - CurrTimeInMins);

                if(lunch>=CurrTimeInMins)
                //
                {t2= new Timer((int)TimeUnit.MINUTES.toMillis(break2), actions2);
                    t2.start();
                    flag=2;
                    t5= new Timer((int)TimeUnit.MINUTES.toMillis(break5), actions5);
                    t5.start();
                    flag=5;}
                else if(lunch<CurrTimeInMins){JOptionPane.showMessageDialog(null,"Tu Lunch ya paso!");}
            }
            catch (Exception ex )
            {System.out.println("No se a seleccionado un Lunch");}
        }
        else

        JOptionPane.showMessageDialog(null,"No ingresaste un Lunch");

        if (!Box3.equals("No Break")){
            try
            {     Date currentTime = new Date();
                String currTime = df6.format(currentTime);
                String[] split = currTime.split(":");
                long CurrTimeInMins= TimeUnit.HOURS.toMinutes(Integer.parseInt(split[0]))+Integer.parseInt(split[1]);

                //Segundo Break
                String[] split3 = Box3.split(":");
                long thirdBreak= TimeUnit.HOURS.toMinutes(Integer.parseInt(split3[0]))+Integer.parseInt(split3[1]);
                //JOptionPane.showMessageDialog(null,"La Hora en minutos es:" + firstBreak);
                // Difference in time

                long break3= (thirdBreak - CurrTimeInMins)-4;
                long break6= (thirdBreak - CurrTimeInMins);

                if(thirdBreak>=CurrTimeInMins)
                //
                //

                { t3= new Timer((int)TimeUnit.MINUTES.toMillis(break3), actions3);
                    t3.start();
                    flag=3;
                    t6= new Timer((int)TimeUnit.MINUTES.toMillis(break6), actions6);
                    t6.start();
                    flag=6;}
                else if(thirdBreak<CurrTimeInMins){JOptionPane.showMessageDialog(null,"Tu otro break ya paso!");}

            }
            catch (Exception ex )
            {System.out.println("No seleccionaste tu segundo break");}
        }
        else

        JOptionPane.showMessageDialog(null,"No seleccionaste tu segundo break");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        Box3 =(String)jComboBox3.getSelectedItem( );
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        Box2 =(String)jComboBox2.getSelectedItem( );
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Box1 =(String)jComboBox1.getSelectedItem( );
    }//GEN-LAST:event_jComboBox1ActionPerformed
       
    public ActionListener actions1 = new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
             JOptionPane.showMessageDialog(null,"Recuerda que tu break es a las "+Box1);
             t1.stop();
           }
       };
    public ActionListener actions2 = new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
             JOptionPane.showMessageDialog(null,"Recuerda que tu Lunch es a las "+Box2);
             t2.stop();
           }
       };
    public ActionListener actions3 = new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
             JOptionPane.showMessageDialog(null,"Recuerda que tu break es a las "+Box3);
             t3.stop();
           }
       };
    public ActionListener actions4 = new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
             JOptionPane.showMessageDialog(null,"Ya te desconectaste? Es hora de tu break");
             t4.stop();
           }
       };
    public ActionListener actions5 = new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
             JOptionPane.showMessageDialog(null,"Ya te desconectaste? Es hora de tu Lunch");
             t5.stop();
           }
       };
    public ActionListener actions6 = new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
             JOptionPane.showMessageDialog(null,"Ya te desconectaste? Es hora de tu break");
             t6.stop();
           }
       };
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetBreak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetBreak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetBreak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetBreak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
            
             new SetBreak().setVisible(true);
             new SetBreak().setDefaultCloseOperation(HIDE_ON_CLOSE);
            }   
        });
             
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    // End of variables declaration//GEN-END:variables

 



}
